version: "3"
services:
  llama-agent-service:
    image: allergy-extraction-service
    env_file: .env
    volumes:
      - /opt/allergy-extraction-service:/app
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: "1m"
        max-file: "30"
