version: "3"
services:
  allergy-extr-serv:
    image: allergy-extraction-service
    env_file: .env
    volumes:
      - /opt/allergy-extraction-service/codes:/app/codes
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: "1m"
        max-file: "30"
