version: "3"
services:
  allergy-extraction-service:
    image: allergy-extraction-service
    env_file: .env
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: "1m"
        max-file: "30"
