name: allergy-extraction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - dataclasses-json=0.6.7
  - distro=1.9.0
  - elastic-transport=8.15.0
  - elasticsearch=8.15.0
  - exceptiongroup=1.2.2
  - frozenlist=1.4.1
  - greenlet=3.0.3
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.8
  - jiter=0.5.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - kafka-python=2.0.2
  - langchain=0.2.16
  - langchain-community=0.2.16
  - langchain-core=0.2.38
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.116
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libffi=3.4.2
  - libgfortran=14.1.0
  - libgfortran5=14.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - marshmallow=3.22.0
  - multidict=6.0.5
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - numpy=1.26.4
  - openai=1.44.0
  - openssl=3.3.2
  - orjson=3.10.7
  - packaging=24.1
  - pip=24.2
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dotenv=1.0.1
  - python_abi=3.10
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=73.0.1
  - sniffio=1.3.1
  - sqlalchemy=2.0.34
  - tenacity=8.5.0
  - tk=8.6.13
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.44.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.11
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - dnspython==2.6.1
      - email-validator==2.2.0
      - fhir-resources==7.1.0
